---
name: "Container-Build"

on:
  # pull_request:

  # push:
  #   tags:
  #     - "*"
  workflow_call:
    inputs:
      go-version:
        description: the go version
        required: false
        type: string
        default: "1.17"
      actions-ref:
        description: the ref actions will be checkout at
        type: string
        required: false
        default: "main"
      image-name:
        description: image name of the container
        type: string
        required: false
        default: ghcr.io/${{ github.repository }}

    secrets:
      token:
        required: true
        description: secret used to check out repository. If actions in this workflow should trigger other actions provice as PAT otherwise the github_token will suffice
jobs:
  build:
    name: "Container image build"
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      packages: "write"

    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v2"
      - name: "☁️ checkout action repository"
        uses: actions/checkout@v2
        with:
          repository: roueslibres1/gh-actions
          ref: ${{inputs.actions-ref}}
          path: .github/actions
      - name: Install tools
        uses: ./.github/actions/install-tools
        with:
          token: ${{secrets.token}}
      - name: "🔧 setup go"
        uses: ./.github/actions/setup-go
        id: setup_go
        with:
          go-version: ${{inputs.go-version}}
          go-tooling-only: "true"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Extract metadata"
        if: "github.event_name == 'push' && github.ref_type == 'tag'"
        id: "metadata_extraction"
        uses: "docker/metadata-action@v3"
        with:
          images: ${{inputs.image-name}}
          tags: |
            type=semver, pattern=v{{ version }}
            type=semver, pattern=v{{ major }}.{{ minor }}
            type=semver, pattern=v{{ major }}
      - name: "Log in to container registry"
        if: "github.event_name == 'push' && github.ref_type == 'tag'"
        uses: "docker/login-action@v1"
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ github.token }}"

      - name: "Build and push container image"
        uses: "docker/build-push-action@v2"
        with:
          tags: "${{ steps.metadata_extraction.outputs.tags }}"
          labels: "${{ steps.metadata_extraction.outputs.labels }}"
          push: "${{ github.event_name == 'push' && github.ref_type == 'tag' }}"
